# Análisis clases latentes #
############################

# Analisis de clases latentes (mediana)

```{r}
load("input/data/proc/cohesion-med-LCA.RData")
```

## Explorar patrones de respuesta
```{r, include = FALSE}
patterns=table(apply(cohesion_med, 1, paste, collapse=""))
patterns
patterns_m=as.data.frame(patterns)
patterns_m <- patterns_m[order(-patterns_m$Freq),] 
patterns_m
```

## Estimar modelo
```{r, include = FALSE}
f <- cbind(conf_interpersonal_med, diversidad_med, lazos_med, identificacion_med, justicia_med, conf_institucional_med, solidaridad_med, participacion_med, cohesion_territorial_med)~1

set.seed(1234)

lca1 <- poLCA(f,cohesion_med, nclass=1,graphs=F, verbose = FALSE)
lca2 <- poLCA(f,cohesion_med, nclass=2,graphs=F, verbose = FALSE) 
lca3 <- poLCA(f,cohesion_med, nclass=3,graphs=F, verbose = FALSE)
lca4 <- poLCA(f,cohesion_med, nclass=4,graphs=F, verbose = FALSE)
lca5 <- poLCA(f,cohesion_med, nclass=5,graphs=F, verbose = FALSE)
lca6 <- poLCA(f,cohesion_med, nclass=6,graphs=F, verbose = FALSE)

## Entropía relativa (4 clases)
##Numerator:
#nume.E <- -sum(lca3$posterior * log(lca3$posterior))
##Denominator (n*log(K)): ## n is a sample size, and K is a number of class
#deno.E <- 1490*log(4)
##Relative Entropy
#Entro <- 1-(nume.E/deno.E)
#Entro
```

##  Estadísticos de ajuste
```{r}
AIC.1 <-as.numeric(lca1$aic)
AIC.2 <-as.numeric(lca2$aic)
AIC.3 <-as.numeric(lca3$aic)
AIC.4 <-as.numeric(lca4$aic)
AIC.5 <-as.numeric(lca5$aic)
AIC.6 <-as.numeric(lca6$aic)

BIC.1 <-as.numeric(lca1$bic)
BIC.2 <-as.numeric(lca2$bic)
BIC.3 <-as.numeric(lca3$bic)
BIC.4 <-as.numeric(lca4$bic)
BIC.5 <-as.numeric(lca5$bic)
BIC.6 <-as.numeric(lca6$bic)

llik.1 <-as.numeric(lca1$llik)
llik.2 <-as.numeric(lca2$llik)
llik.3 <-as.numeric(lca3$llik)
llik.4 <-as.numeric(lca4$llik)
llik.5 <-as.numeric(lca5$llik)
llik.6 <-as.numeric(lca6$llik)

chisq.1 <- as.numeric(lca1$Chisq)
chisq.2 <- as.numeric(lca2$Chisq)
chisq.3 <- as.numeric(lca3$Chisq)
chisq.4 <- as.numeric(lca4$Chisq)
chisq.5 <- as.numeric(lca5$Chisq)
chisq.6 <- as.numeric(lca6$Chisq)

G.1 <- as.numeric(lca1$Gsq)
G.2 <- as.numeric(lca2$Gsq)
G.3 <- as.numeric(lca3$Gsq)
G.4 <- as.numeric(lca4$Gsq)
G.5 <- as.numeric(lca5$Gsq)
G.6 <- as.numeric(lca6$Gsq)

n.obs1 <- as.numeric(lca1$Nobs)
n.obs2 <- as.numeric(lca2$Nobs)
n.obs3 <- as.numeric(lca3$Nobs)
n.obs4 <- as.numeric(lca4$Nobs)
n.obs5 <- as.numeric(lca5$Nobs)
n.obs6 <- as.numeric(lca6$Nobs)

#Creación de Vectores para TABLA DE COMPARACIÓN
AIC <- c(AIC.1, AIC.2,AIC.3,AIC.4,AIC.5, AIC.6)
BIC <- c(BIC.1, BIC.2,BIC.3,BIC.4,BIC.5, BIC.6)
llik <- c(llik.1, llik.2,llik.3,llik.4,llik.5, llik.6)
chi.cuadrado <- c(chisq.1, chisq.2,chisq.3,chisq.4,chisq.5, chisq.6)
G2 <- c(G.1, G.2,G.3,G.4,G.5, G.6)
N <- c(n.obs1, n.obs2,n.obs3,n.obs4,n.obs5, n.obs6)
Modelos <- c("1 clase", "2 clases", "3 clases", "4 clases", "5 clases", "6 clases")

#CREACIÓN TABLA ESTADÍSTICOS DE AJUSTE MODELOS TODAS LAS VARIABLES
fit.indices <- data.frame(Modelos,AIC,BIC,llik,chi.cuadrado,G2,N)
fit.indices
```

## Ordenar las clases
```{r}
#Extraer valores de inicio (modelo seleccionado)
probs.start<-lca4$probs.start
#lca5$probs.start

#Reanalizar con gráficos
# lca4<-poLCA(f, cohesion_med, nclass=4, probs.start=probs.start,graphs=TRUE, na.rm=TRUE, maxiter=3000)

  # Graph latent classes, 3 clases
  lca3_probs=as.data.frame(lca3$probs)
  dim(lca3_probs)
  names(lca3_probs)
  datlca_tot_par=lca3_probs[c(2,4,6,8,10,12,14,16,18)] #dejar solo prob "si"
  datlca_tot_par$class=c(1:3) # añadir número de clase
  library(reshape2)
  datlca_tot_parl=melt(datlca_tot_par, id=c("class") )
  str(datlca_tot_parl)
  print(levels(datlca_tot_parl$variable))
  
    # Relabel factors
    datlca_tot_parl$variable=factor(datlca_tot_parl$variable, labels=c("Confianza", "Diversidad", "Lazos", "Identificación", "Justicia", "Conf. Instituciones","Solidaridad", "Participación", "Vecinal"))
    lca3$P # class size
    datlca_tot_parl$class=factor(datlca_tot_parl$class,labels=c("Clase 1 (32%)", "Clase 2 (42%)", "Clase 3 (26%)"))

    library(ggplot2)
lca3_graph <-ggplot(data = datlca_tot_parl, aes(x=variable, y=value, group=class, shape=class)) + 
      geom_line(aes(linetype=class)) + geom_point(size = 2) +
      ggtitle("Clases latentes de Cohesión Social") + 
      xlab("Indicadores Cohesión") + 
      ylab("Probabilidades condicionales")
    
lca3_graph
    
ggsave("output/graphs/lca3.jpg", plot = lca3_graph, height=4, width=10, units="in", dpi=350 )





  # Graph latent classes, 4 clases
  lca4_probs=as.data.frame(lca4$probs)
  dim(lca4_probs)
  names(lca4_probs)
  datlca_tot_par=lca4_probs[c(2,4,6,8,10,12,14,16,18)] #dejar solo prob "si"
  datlca_tot_par$class=c(1:4) # añadir número de clase
  library(reshape2)
  datlca_tot_parl=melt(datlca_tot_par, id=c("class") )
  str(datlca_tot_parl)
  print(levels(datlca_tot_parl$variable))
  
    # Relabel factors
    datlca_tot_parl$variable=factor(datlca_tot_parl$variable, labels=c("Confianza", "Diversidad", "Lazos", "Identificación", "Justicia", "Conf. Instituciones","Solidaridad", "Participación", "Vecinal"))
    lca4$P # class size
    datlca_tot_parl$class=factor(datlca_tot_parl$class,labels=c("Clase 1 (25%)", "Clase 2 (21%)", "Clase 3 (28%)", "Clase 4 (26%)"))

    library(ggplot2)
lca4_graph <-ggplot(data = datlca_tot_parl, aes(x=variable, y=value, group=class, shape=class)) + 
      geom_line(aes(linetype=class)) + geom_point(size = 2) +
      ggtitle("Clases latentes de Cohesión Social") + 
      xlab("Indicadores Cohesión") + 
      ylab("Probabilidades condicionales")
    
lca4_graph
    
ggsave("output/graphs/lca4.jpg", plot = lca4_graph, height=4, width=10, units="in", dpi=350 )

#Reordnar clases, si es necesario
#new.probs.start<-poLCA.reorder(probs.start, c(2,1,3,4))

#Re-estimar para nuevo orden
#lca4<-poLCA(f, elsoc, nclass=4, probs.start=new.probs.start, graphs=TRUE, na.rm=TRUE)
```

```{r}
probs.start<-lca5$probs.start

lca5<-poLCA(f, cohesion_med, nclass=5, probs.start=probs.start,graphs=TRUE, na.rm=TRUE, maxiter=3000)
```



# Analisis de clases latentes (media)

## Explorar patrones de respuesta
```{r, include = FALSE}
patterns=table(apply(cohesion_mean, 1, paste, collapse=""))
patterns
patterns_m=as.data.frame(patterns)
patterns_m <- patterns_m[order(-patterns_m$Freq),] 
patterns_m
```

## Estimar modelo
```{r, include = FALSE}
f <- cbind(conf_interpersonal_mean, diversidad_mean, lazos_mean, identificacion_mean, justicia_mean, conf_institucional_mean, solidaridad_mean, participacion_mean, cohesion_territorial_mean)~1

set.seed(1234)

lca1 <- poLCA(f,cohesion_mean, nclass=1,graphs=F)
lca2 <- poLCA(f,cohesion_mean, nclass=2,graphs=F) 
lca3 <- poLCA(f,cohesion_mean, nclass=3,graphs=F)
lca4 <- poLCA(f,cohesion_mean, nclass=4,graphs=F)
lca5 <- poLCA(f,cohesion_mean, nclass=5,graphs=F)
lca6 <- poLCA(f,cohesion_mean, nclass=6,graphs=F)

## Entropía relativa (4 clases)
##Numerator:
#nume.E <- -sum(lca3$posterior * log(lca3$posterior))
##Denominator (n*log(K)): ## n is a sample size, and K is a number of class
#deno.E <- 1490*log(4)
##Relative Entropy
#Entro <- 1-(nume.E/deno.E)
#Entro
```

##  Estadísticos de ajuste
```{r}
AIC.1 <-as.numeric(lca1$aic)
AIC.2 <-as.numeric(lca2$aic)
AIC.3 <-as.numeric(lca3$aic)
AIC.4 <-as.numeric(lca4$aic)
AIC.5 <-as.numeric(lca5$aic)
AIC.6 <-as.numeric(lca6$aic)

BIC.1 <-as.numeric(lca1$bic)
BIC.2 <-as.numeric(lca2$bic)
BIC.3 <-as.numeric(lca3$bic)
BIC.4 <-as.numeric(lca4$bic)
BIC.5 <-as.numeric(lca5$bic)
BIC.6 <-as.numeric(lca6$bic)

llik.1 <-as.numeric(lca1$llik)
llik.2 <-as.numeric(lca2$llik)
llik.3 <-as.numeric(lca3$llik)
llik.4 <-as.numeric(lca4$llik)
llik.5 <-as.numeric(lca5$llik)
llik.6 <-as.numeric(lca6$llik)

chisq.1 <- as.numeric(lca1$Chisq)
chisq.2 <- as.numeric(lca2$Chisq)
chisq.3 <- as.numeric(lca3$Chisq)
chisq.4 <- as.numeric(lca4$Chisq)
chisq.5 <- as.numeric(lca5$Chisq)
chisq.6 <- as.numeric(lca6$Chisq)

G.1 <- as.numeric(lca1$Gsq)
G.2 <- as.numeric(lca2$Gsq)
G.3 <- as.numeric(lca3$Gsq)
G.4 <- as.numeric(lca4$Gsq)
G.5 <- as.numeric(lca5$Gsq)
G.6 <- as.numeric(lca6$Gsq)

n.obs1 <- as.numeric(lca1$Nobs)
n.obs2 <- as.numeric(lca2$Nobs)
n.obs3 <- as.numeric(lca3$Nobs)
n.obs4 <- as.numeric(lca4$Nobs)
n.obs5 <- as.numeric(lca5$Nobs)
n.obs6 <- as.numeric(lca6$Nobs)

#Creación de Vectores para TABLA DE COMPARACIÓN
AIC <- c(AIC.1, AIC.2,AIC.3,AIC.4,AIC.5, AIC.6)
BIC <- c(BIC.1, BIC.2,BIC.3,BIC.4,BIC.5, BIC.6)
llik <- c(llik.1, llik.2,llik.3,llik.4,llik.5, llik.6)
chi.cuadrado <- c(chisq.1, chisq.2,chisq.3,chisq.4,chisq.5, chisq.6)
G2 <- c(G.1, G.2,G.3,G.4,G.5, G.6)
N <- c(n.obs1, n.obs2,n.obs3,n.obs4,n.obs5, n.obs6)
Modelos <- c("1 clase", "2 clases", "3 clases", "4 clases", "5 clases", "6 clases")

#CREACIÓN TABLA ESTADÍSTICOS DE AJUSTE MODELOS TODAS LAS VARIABLES
fit.indices <- data.frame(Modelos,AIC,BIC,llik,chi.cuadrado,G2,N)
fit.indices
```

## Ordenar las clases
```{r}
#Extraer valores de inicio (modelo seleccionado)
probs.start<-lca4$probs.start
#lca5$probs.start

#Reanalizar con gráficos
lca4<-poLCA(f, cohesion_mean, nclass=4, probs.start=probs.start,graphs=TRUE, na.rm=TRUE, maxiter=3000)

#Reordnar clases, si es necesario
#new.probs.start<-poLCA.reorder(probs.start, c(2,1,3,4))

#Re-estimar para nuevo orden
#lca4<-poLCA(f, elsoc, nclass=4, probs.start=new.probs.start, graphs=TRUE, na.rm=TRUE)
```

```{r}
probs.start<-lca5$probs.start

lca5<-poLCA(f, cohesion_mean, nclass=5, probs.start=probs.start,graphs=TRUE, na.rm=TRUE, maxiter=3000)
```