---
editor_options:
  markdown:
    wrap: 72
---

# Introducción {-}

<div style="text-align: justify">

El interés por el estudio de la cohesión social posee una larga trayectoria tanto académica como así también desde el estado y de organizaciones con interés público. La cohesión social aparece como una aspiración normativa de una sociedad mejor, vinculada a conceptos como lazos sociales de calidad, pertenencia, y confianza en los demás y en el estado. Se asume también que un estado de adecuada cohesión social es producto de condiciones estructurales y políticas que apunten a mayor igualdad, integración y oportunidades, por lo cual muchas veces se refiere a ella como un horizonte o una consecuencia de buenas políticas sociales. Este interés se ha plasmado en una serie de proyectos internacionales y nacionales que estudian la cohesión social. Por el lado internacional son reconocidas iniciativas como Mapping social Cohesion en Canadá [@jenson_mapping_1998] el Scanlon-Monash Cohesion Index en Autralia [@markus_mapping_2014], el Radar de Cohesión Social en Alemania [@dragolov_social_2013], y el proyecto Ecosocial en América Latina [@tironibarrios_redes_2008; @valenzuela_vinculos_2008]. En el caso de organizaciones internacionales con foco en América Latina destaca la amplia tradición de la CEPAL en estudios de cohesión social [@cepal_america_2010; @cepal_cohesion_2010; @cepal_cohesion_2021; @maldonado_inclusion_2020; @sojo_cohesion_2007; @villatoros._sistema_2008].

Muchos de los estudios en cohesión social han tenido como foco su definición y también la búsqueda de indicadores para poder caracterizar distintas sociedades respecto a sus niveles de cohesión social en sus múltiples dimensiones. Parte de este objetivo lo comparte el Centro de Estudios de Conflicto y Cohesión Social (COES), al cual pertenecen las/os autores de este trabajo, y que dados los intereses comunes con CEPAL han venido trabajando hace algunos años en distintas iniciativas, tales como el informe sobre Clases Medias y Cohesión Social  publicado por CEPAL [@barozet_clases_2021]. El presente trabajo se enmarca en esta relación de colaboración y se enfoca en la definición y medición de indicadores de cohesión social basado en el concepto de cohesión social recientemente actualizado por la CEPAL [@cepal_cohesion_2021] que señala que:

**“la cohesión social puede ser comprendida como la capacidad de una  sociedad y sus instituciones democráticas de promover relaciones sociales de igualdad y generar un sentido de  pertenencia y una orientación hacia el bien común de una forma percibida como legítima por sus miembros. Esa  capacidad requiere de la existencia de garantías de bienestar, la promoción activa de una cultura de la  igualdad, de mecanismos para la reducción de las desigualdades, de reconocimiento, de participación y para  la resolución pacífica de conflictos y adaptación a cambios, en el marco de un Estado de derecho y una  democracia de calidad”**. [@cepal_cohesion_2021]

La primera parte de esta definición de cohesión social como capacidad hace referencia a una serie de elementos constitutivos del concepto de cohesión social, y que se pueden encontrar en otras definiciones contemporáneas de cohesión como las del [Radar de la Cohesión Social](https://www.bertelsmann-stiftung.de/en/publications/publication/did/social-cohesion-radar/) y las del [Consejo Asesor para la Cohesión Social](https://www.desarrollosocialyfamilia.gob.cl/storage/docs/Informe_Final_Consejo_Cohesion_Social.pdf) desarrollada en Chile el año 2020, y que entienden la cohesión como un fenómeno multidimensional. Gran parte de la literatura y estudios empíricos a la fecha en el área se han enfocado en generar mediciones e indicadores para cada una de estas subdimensiones, para lo cual muchas veces utilizan datos secundarios de encuestas nacionales e internacionales y así realizar un diagnóstico del estado de la cohesión social. En esta línea la CEPAL ha realizado distintas iniciativas de carácter regional en torno al concepto de cohesión social, y el interés en abordar en particular el caso Chileno en este reporte es poder utilizar fuentes de información más especializadas que las disponibles a nivel regional (América Latina), así como explorar aspectos que no abarcados en análisis regionales y que se pueden abordar teniendo una unidad de análisis nacional. Por ejemplo, el análisis nacional permite atender a unidades subterritoriales/subnacionales así como también el desarrollo de tipologías específicas de cohesión social en un país que van más allá de la mera comparación de promedios nacionales. 

En Chile es posible identificar dos estudios específicos que se han abocado a la medición de los elementos constitutivos de la cohesión social basados en encuestas: Ecosocial [@valenzuela_vinculos_2008] y [ELSOC](https://coes.cl/encuesta-panel/)(Estudio Longitudinal Social de Chile). Ecosocial es proyecto que contempló el desarrollo de una encuesta "construida con el propósito de medir y documentar una serie de aspectos relacionados con el estado de la cohesión social en la población de las principales ciudades de siete países Latinoamericanos: Argentina, Brasil, Colombia, Chile, Guatemala, México y Perú." [@valenzuela_vinculos_2008, p.5]. Los resultados de esta encuesta han sido publicados en libros como ["Vínculos, Creencias e Ilusiones"](https://www.cieplan.org/wp-content/uploads/2019/12/Libro_Completo_Vinculos_Creencia_e_Ilusiones.pdf) (2008), en conexión con otros trabajos también de CIEPLAN centrados en cohesión como el libro ["Redes, Estado y Mercado"](https://www.cieplan.org/wp-content/uploads/2019/12/Libro_Completo_Redes_Estado_y_Mercado_compressed.pdf)(2008). En cuanto a la encuesta [ELSOC](https://coes.cl/encuesta-panel/), es un panel longitudinal desarrollado por el Centro de Estudios de Conflicto y Cohesión Social [COES](https://www.coes.cl/) desde el año 2016, y que será la base de datos principal para el presente estudio dado su carácter longitudinal que permite analizar cambios en la cohesión social en el tiempo.

El principal objetivo de la encuesta ELSOC es evaluar la manera como piensan, sienten y se comportan las y los chilenos en torno a un conjunto de temas referidos al conflicto y la cohesión social en Chile. Además, permite comparar la estabilidad o cambio en diversas dimensiones sociales atendiendo a factores que los moderan o explican a lo largo de los años. Para ello se encuesta anualmente desde el año 2016 a alrededor de 3.000 personas de manera longitudinal mediante panel, es decir, todos los años se encuesta a las mismas personas para así analizar cambios en trayectorias individuales en distintas dimensiones. Los temas abordados  en esta encuesta así como su naturaleza longitudinal la hacen única en el país y permite despejar una serie de preguntas sobre cambio social que no pueden ser abordadas con precisión con la comparación de encuestas repetidas en el tiempo a distintos sujetos (mayores detalles de este estudio se presentan al principio del capítulo 1).

El presente documento se estructura en tres capítulos principales. El primer capítulo está abocado a la medición de la cohesión social, donde se generan indicadores basados en la encuesta ELSOC para las distintas subdimensiones de cohesión social propuestas por CEPAL. El segundo capítulo toma estos indicadores por dimensión y subdimensión y analiza su cambio/estabilidad en el tiempo en Chile entre 2016 y 2020. Finalmente, el capítulo 3 ahonda en los distintos tipos o clases de cohesión social y su relación con factores individuales y territoriales en Chile.
