---
editor_options:
  markdown:
    wrap: 72
---

<div style="text-align: justify">

# Conclusiones {-}

La realización de este trabajo sobre la medición y análisis de cambios en la cohesión social en Chile implicó avanzar en una serie de ámbitos. El punto de partida de esta investigación consistió en un concepto multidimensional de cohesión social propuesto por la CEPAL, que establece una serie de desafíos para su operacionalización y medición considerando su estructura de tres dimensiones y nueve subdimensiones. Para llevar a cabo esta tarea inicial de medición y generación de indicadores utilizamos los datos de la encuesta longitudinal ELSOC de COES que, si bien ofrece ventajas únicas para el análisis de cambio en el tiempo en indicadores de cohesión social, no fue diseñada específicamente para medir el concepto de cohesión de la CEPAL. Esto requirió un trabajo importante de ajuste entre marco conceptual e indicadores, desarrollado en el capítulo uno. Dedicar tiempo a temas de medición no es lo habitual en reportes con datos sociales, ya que en general el foco está en realizar cruces entre indicadores y otras variables de interés. Sin embargo, el trabajo de medición reportado en el Capítulo 1 de este informe pareció necesario ya que - en línea con lo desarrollado  anteriormente por Ecosocial, COES, y el Consejo Asesor para la Cohesión Social - sienta las bases para futuros estudios sobre cohesión social en el país y esperamos puedan ser perfeccionados en el futuro para así otorgar mayor validez a las mediciones. Esto es relevante sobre todo al momento de realizar análisis del cambio social, ya que como dice el refrán "si quieres medir el cambio, no cambies las medidas".

Junto al desafío de la generación y medición de indicadores para la cohesión social con datos de encuesta, un segundo aspecto central de este informe es el análisis del cambio en los indicadores de cohesión social en el tiempo. Si bien hay proyectos internacionales que abordan el cambio en indicadores de cohesion (como el índice de Scanlon-Monash en Australia), en nuestro caso analizamos el cambio intraindividual mediante una encuesta panel longitudinal como ELSOC, que encuesta a las mismas personas año a año. Hasta nuestro conocimiento no hay antecedentes en la literatura nacional ni internacional de un análisis de este tipo, siendo lo más cercano el piloto de panel de cohesión social que se está desarrollando actualmente en Alemania por parte del [Research Institute for Social Cohesion (RISC)](https://www.fgz-risc.de/), cuyos resultados preliminares fueron presentados en septiembre 2021 en la conferencia "Cohesive Societies" de la Akademie für Soziologie. Por lo tanto, con los análisis presentados en el Capítulo 2, por primera vez ofrecemos una perspectiva de cómo cambian las percepciones y opiniones de las personas en las distintas dimensiones de cohesión social en Chile de manera longitudinal. Así, observamos que los niveles de cohesión son relativamente estables en términos de frecuencias comparativas año a año, aún cuando existe una importante variabildad y movimiento de personas entre los distintos niveles de los indicadores. Es de esperar que estudios posteriores puedan entregar mayores luces sobre las dinámicas de la cohesión social a las que nos aproximamos preliminarmente y que ofrecen un gran potencial de agendas de investigación a futuro.

Junto a la generación de indicadores y al análisis longitudinal, en la última parte de este reporte se estudian los factores que podrían estar afectando la cohesión social en Chile. Dado que la existencia de nueve dimensiones distintas de cohesión hace muy difícil mantener el foco en el concepto de cohesión y sus factores habilitadores, en el capítulo tres estimamos perfiles de cohesión social en la población mediante la técnica estadística de análisis de clases latentes, una propuesta conceptual y metodológica que hasta nuestro conocimiento no ha sido utilizada previamente en estudios de cohesión social. La estimación de tres clases o tipos de cohesión social (movilizados, legitimantes y atomizados) permite no solo resumir la información de las nueve dimensiones de cohesión en un esquema conciso y con contenido sustantivo, sino también ayuda a identificar de mejor manera qué elementos habilitadores e ihnibidores de la cohesión social se relacionan más estrechamente con cada uno de estos tres pefiles. Además, la tipología de cohesión social permitió en primer lugar realizar análisis identificar diferencias comparativas entre las regiones de Chile, así como también diferencias claras de factores socio-estructurales entre las distintas clases de cohesión social. Sin embargo, dado que la tipología de cohesión social desarrollada en este capítulo posee un carácter preliminar y exploratorio es de esperar que nuevas investigaciones con otros datos puedan someter a constraste esta propuesta y generar mayor evidencia para su validación.

Finalmente, nos parece importante manifestar que la innovación metodológica y conceptual de un trabajo como este no es necesariamente un sinónimo de relevancia y de calidad. Dado que la actividad científica se puede describir como el escepticismo organizado [@merton_sociology_1973], nuestra aspiración es que lo presentado aquí quede permanentemente abierto a la crítica, comentarios y propuestas de mejora. Por esta razón, este estudio ha sido realizado en un marco de ciencia abierta, donde los datos, códigos de análisis y texto se encuentran en un repositorio público [(https://github.com/ocscoes/cohesion-cepal)](https://github.com/ocscoes/cohesion-cepal) de modo que quien se interese por revisar, replicar o corregir lo acá expuesto pueda hacerlo con la mayor facilidad y transparencia posible.
