---
title: "Cambios en la Cohesión Social en Chile"
subtitle: ""
author: "Equipo CEPAL-ELSOC"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [bib/cohesion-cepal-elsoc.bib, packages.bib, book-ocs.bib]
biblio-style: apalike
link-citations: yes
linkcolor: blue
# description: "This is a minimal example of using the bookdown package to write a book. The output format for this example is bookdown::gitbook."
geometry: "left=4cm, right=3cm, top=2.5cm, bottom=2.5cm"
fontsize: 12pt
linestretch: 1.5
toc-depth: 1
lof: True
lot: True
# lang: es
github-repo: "Kevin-carrasco/cohesion-cepal"
url: "https://kevin-carrasco.github.io/cohesion-cepal/"
always_allow_html: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE,message = FALSE, cache = FALSE,out.width = '75%',fig.pos= "H",fig.align = 'center')
# knitr::opts_knit$set(base.url = "../") #relative path for .html output file
# knitr::opts_knit$set(root.dir = "../") #relative path for chunks within .rmd files
options(scipen=999)
rm(list=ls())
options(knitr.kable.NA = '',linesep = "")
options(knitr.graphics.error = FALSE)
# Sys.setlocale("LC_ALL", "ES_ES.UTF-8")
```

```{r message=FALSE, warning=FALSE, include=FALSE, echo=FALSE}
pacman::p_load(knitr, kableExtra, dplyr,flextable,pander)
```

```{r echo=FALSE }
is_word_output <- function(fmt = knitr:::pandoc_to()) {
  length(fmt) == 1 && fmt == "docx"
}

table_format = if(is_html_output()) {
  "html"
} else if(is_latex_output()) {
  "latex"
}

eval01 = if(is_html_output() | is_latex_output()) {T} else {F}


fullw = if(is_html_output()) {T} else if(is_latex_output()) {F}
fsize = if(is_html_output()) {14} else if(is_latex_output()) {8}
```

# Presentación {-}

Este reporte de investigación consiste en un análisis de medición y cambios en la cohesión social en Chile en base a indicadores de la Encuesta Longitudinal Social de Chile - [ELSOC](https://coes.cl/encuesta-panel/), producida por [COES](https://coes.cl/)

Autores:

- Juan Carlos Castillo
- Emmanuelle Barozet
- Vicente Espinoza

Ayudante de investigación: Kevin Carrasco.
